### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by reziakk** [amazon-connect/amazon-connect-chat-ui-examples#136] opened 2023-07-25 14:59 UTC
I'm trying to change the font-size inside the chat content area.
I've made modifications at ChatWidget styled.js file line 101 to: text-size: 0.420rem
Also tried to do it, modifying the amazon-connect-chat-interfact but still it keeps at 14px font-size

**Comment by mliao95** [comment] 2023-07-25 20:36
Hey @reziakk !

The chat content area is defined as the [ChatTranscriptor](https://github.com/amazon-connect/amazon-connect-chat-interface/tree/master/src/components/Chat/ChatTranscriptor) component in our [amazon-connect-chat-interface ](https://github.com/amazon-connect/amazon-connect-chat-interface/tree/master) repository.

If you want to make modifications to the ChatTranscriptor's font-size, you would need to do so there. You can check out that repository, make your font-size changes, build the repository using `npm run release` and then replace the bundled `amazon-connect-chat-interface.js` file found at `amazon-connect-chat-interface/build/dist/static/js/amazon-connect-chat-interface.js` into your public folder [here](https://github.com/amazon-connect/amazon-connect-chat-ui-examples/tree/master/customChatWidget/public).

Let me know if you have any more questions.

**Comment by mliao95** [comment] 2023-07-28 01:19
Resolved.  Dupe of https://github.com/amazon-connect/amazon-connect-chat-interface/issues/159

**Closed by mliao95** 2023-07-28 01:19 UTC
Labels: ⌛️ Awaiting Response
